---
version: '3.8'

services:
  app:
    build:
      context: ..  # Build context is set to parent directory
      dockerfile: development-container/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/app  # Mount parent directory
      - go-modules:/go/pkg/mod
      - tmp-air:/app/tmp

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - REDIS_PASSWORD=""
      - REDIS_DB=0
      # PostgreSQL environment variables
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=brianwu291
      - DB_NAME=motor-rental
      - DB_PASSWORD=
      - DB_MAX_POOL_CONS=100
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=motor-rental
      - POSTGRES_USER=brianwu291
      - POSTGRES_HOST_AUTH_METHOD=trust  # Allows connections without password for local dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brianwu291 -d motor-rental"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  go-modules:
  redis-data:
  tmp-air: # volume for Air's temporary files
  postgres-data:  # Persistent volume for PostgreSQL data
